### ISSUE TITLE
CountdownCube

### ISSUE THREAD

**Issue by attora** [oofaish/countdownCube#1]
Problem with Hours

**Comment by attora** [comment]
The cube hours has wrong result in term of countdown.

**Comment by oofaish** [comment]
Can you give me an example please?

**Comment by attora** [comment]
Hi,
Thnaks for reply, this is the code
 $(function () {
            $('#counter').countdownCube( {
                target: new Date( 'November 04, 2015 13:30:00' ),
                cubeSize: 50,
                background: 'rgba( 255, 150, 150, 0.8 )',
                color: 'white',
            });
            });

the result is simply wrong because it show me wrong hours in the browser.
You have to try with the same day in target to see a diffrece.

Other question, 3D doesnt work in mu IE10, even if I put this compatibilty code in the head :
meta http-equiv="X-UA-Compatible" content="IE=edge"
Even your home page countdown 3d http://www.cigari.co.uk/countdown/ not working in IE10
thanks

**Comment by kayaz** [comment]
Fix:

`var diff = ( options.target - now ) / 1000.0;diff = diff - 3600;`

**Comment by CristianCantoro** [comment]
This is probably fixed by https://github.com/oofaish/countdownCube/pull/5 now.
