### ISSUE TITLE
Other language support

### ISSUE THREAD

**Issue by jgb-solutions** [oofaish/countdownCube#2]
Hello! Is there an option to translate the Year, Month, Day, Hours, Minute and Seconds.

Because I'm using it on site that is in french and I would like to translate the countdown in french.

So I was wondering there is a way to do it or you're planning to add the feature. Yes I know I can hardcode it myself but hacking the code plugin is still not a good practice.

But anyways thanks a lot for your plugin. It works great!

**Comment by oofaish** [comment]
Not looking at it now I am afraid - feel free to propose a change, and I am happy to review it, but no time right now to look at it now.

**Comment by jgb-solutions** [comment]
Alright then. Thanks for responding! I'll fork it and modify it as needed. And maybe do a pull request.
Regards!

**Comment by CristianCantoro** [comment]
Pull request https://github.com/oofaish/countdownCube/pull/3 solves this issue as well.

**Comment by CristianCantoro** [comment]
Pull request was merged in https://github.com/oofaish/countdownCube/commit/4351e47022c373c995ca5baa32f60aed1addfc9e, this is now fixed.
