### ISSUE TITLE
onEnd callback error

### ISSUE THREAD

**Issue by Hamidnch** [oofaish/countdownCube#9]
Hi.
Thanks for sharing your job.
I'm facing with error after using this plugin.
The error content is:
countdownCube.min.js:1 Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.onEndCallback (countdownCube.min.js:1)
    at Object.setTimeLeft (countdownCube.min.js:1)
    at countdownCube.min.js:1

onEndCallback | @ | countdownCube.min.js:1
-- | -- | --
  | setTimeLeft | @ | countdownCube.min.js:1
  | (anonymous) | @ | countdownCube.min.js:1
  | setTimeout (async) |   |  
  | init | @ | countdownCube.min.js:1
  | Plugin | @ | countdownCube.min.js:1
  | (anonymous) | @ | countdownCube.min.js:1
  | each | @ | jquery-3.3.1.min.js:2
  | each | @ | jquery-3.3.1.min.js:2
  | $.fn.countdownCube | @ | countdownCube.min.js:1
  | (anonymous) | @ | (index):328

Thanks a lot.

**Comment by oofaish** [comment]
closing as I assume the author has moved on - sorry I never got to it when you initially posted.
